### PR TITLE
Fix #73 : Catch codeObject rendering failure at playground full update

### LINKED ISSUE #73: invalid code makes rendering stop for the rest of objects in the list
_Tested in a classroom environnement with 22 students and 22-26 code objects:_ 
Only the Code Objects up to an (unknown) invalid Code Object will render, creating confusion and frustration because many objects will not appear. Strangely, some renderer will appear to be immune, when in fact they are stuck and not updating. Other renderer will update and show just a few objects. The source of the problem will be at first, and quite erroneously, attributed to the fabled bad networks of schools. The first invalid code will of course be in an object a the top of the list, making only 3 objects appearing. This will lead to the solution. But then more invalid code will be there, in abandoned test code. Students will be at the edge of rebelling against the teacher. "Is he of any competence?", they will think, starting to wonder if the trust they put in him to guide them on the path of creative coding was well placed. The teacher will react by frantically searching for bugs in the 22 code objects, and will ultimately ressort to delete objects that seem to have no proper owner. 

**How to reproduce** 
Send good code in 2 or 3 objects
Send an other code object that is invalid from the start, example: no { } at all for `void draw() {}` or a part of a function in the middle of nowhere.
Send more new code objects that will appears further down the list, after the bad code object. These will not render.

**Workaround** Not much. Ask each participant to test its own code on a separate Playground. Identify abandoned objects with partial code and delete them.

### PR DESCRIPTION
**Pull request by etienneCharignon**
If the error is not cached other code object will not be rendered during full playground update.

This fix issue #73

By the way I added a error log making it easier for the teacher to identify the falty code object.

### CODE REVIEW

**Comment by jonathanperret** [comment]
Good _catch_ @etienneCharignon ! 😂

However as I was saying in #73 , what made this bug elusive for the longest time (I believe #26 was the same issue, and it’s more than two years old!) is the fact we have two ways of setup the rendering of an object (either as an existing object when loading the playground, or as a new object in an already-loaded playground). And I worry that the proposed patch accentuates that divergence by handling errors in the former case but not in the latter.

While removing the `playground full update` event would be an interesting way of getting rid of the duplication entirely, I suggest that just doing the error handling in the `updateObject` function would be enough to make it consistent.

File: public/paysagerenderer.js [hunk 1]
```diff
@@ -89,12 +85,16 @@ function createLayer (targetCanvas, code) {
...
   // to set width and height correctly before setup() runs.
+  try {
   var sketch = window.Processing.compile(code);
   sketch.onLoad = resize;
   var newLayer = new window.Processing(targetCanvas, sketch);
   setDefaultBackgroundToTransparent(newLayer);
   patchBackgroundFunctionToBeTransparentByDefault(newLayer);
   return newLayer;
+  } catch (e) {
+      console.error('Error in code object ' + targetCanvas + '. Code not rendered. ' + e);
```
Comment (jonathanperret) [inline public/paysagerenderer.js]: Apart from the broken indents that ESLint caught, I really was thinking of `updateObject` rather than `createLayer` for the `catch`. Among other things, you don’t have the object ID in `createLayer`, so the error message is bound to be ugly.

**Comment by juliendorra** [comment]
Wouldn't it be better to catch the error a the source (when we ask the code to be compiled)?
What would be the advantage of catching the error later in the function call chain?
(I added a commit that log the id properly)

**Comment by etienneCharignon** [comment]
I did handle the error in the full update only because I was not sure that we wanted to handle the error the same way every where… To me the problem reported was specific to the case of the full update (the behaviour was correct in case of a single code object update, wasn't it ?)

But that might be ok to move it up as @juliendorra did but that do change somehow how we update code object. 

Do we still can recover from a faulty code object  in both cases ? 

Actually, we get a "Cannot read property 'size' of undefined" error ligne 42 (42 really!) of paysagerenderer.js when calling a full reload after summiting a faulty code.

I'm missing some automated testing here…

**Comment by juliendorra** [comment]
Indeed it's the canvas ID :-) but they are derived/identical and it's a nice proxy for the code objet ID (it seems sufficient for logging a syntax error event)
(and if I remember it well there's other places in the code where we use the fact that HTML attributes store useful values and use them as proxy values )

I'm worried that not catching the error early, at the compile call, might be confusing for future contributors/readers and against some locality precept on organizing things.

Of course I am not used to error catching at all (!!) so my worry might be misplaced :-)

**Comment by jonathanperret** [comment]
I disagree with canvas element ID being an OK proxy for object ID. The log message is a lie. I don’t even remember why there is an ID attribute on the canvas elements; they could go away anytime.

I also think we should stop relying on information from the DOM (see e.g. https://medium.com/@sstur/the-dom-is-not-a-datastore-7a17b10d6705 ).

Error handling is hard… a couple guidelines I try to go by:
1. Don’t catch exceptions unless you know what you’re going to do with them (“swallowing” (just logging) them is only OK in rare circumstances, they should generally be rethrown)
2. Errors caught higher up the stack are more meaningful (e.g. you know which object you were updating), those caught lower are more precise (e.g. you could know whether there was an error during compilation, setup or another step of the update)

The reason we’re here is because the “full update” loop is one of those rare cases alluded to in 1 : updating the objects should not stop because one of them failed. However, going any lower than the `for` loop we both lose in meaning (which object was that?) and create a risk of the bug popping up again (what if an error occurs in `updateObject` but outside of `createLayer`? We’d be back to square one with an update stopping mid-list).

Based on the previous paragraph it would seem I’d recommend putting the `try … catch` statement in the `for` loop as @etienneCharignon originally did! However if you also take into account the fact that`updateObject` is called in another context, where there is no reason not to log the same error message for the same cause, you realize that every `updateObject` call would end up wrapped in the same exception handler. Hence the suggested compromise: to put the handler around the body of `updateObject`. Perhaps it would be clearer to introduce a `safelyUpdateObject` function, called everywhere instead of `updateObject`, and which would just wrap a call `updateObject` in `try … catch`.

Here’s hoping I’m finally coming through…😐

**Comment by etienneCharignon** [comment]
What about separating logging and error control ? we could add a `try…catch` for logging in `createLayer` or better in `updateObject` but re-throw the exception and then catch it and swallow in the full update.

**Comment by juliendorra** [comment]
Is the current patch ready for merging? If there's no more remarks, I'll merge it.

**Comment by jonathanperret** [comment]
Squashed and merged. Thanks everyone! 🙏🏻

File: public/paysagerenderer.js [hunk 2]
```diff
@@ -65,20 +65,24 @@ function patchBackgroundFunctionToBeTransparentByDefault (layer) {
...
+    } else {
+      console.log('canvas reused for ' + id);
+      try {
+        layers[id].exit();
+      } catch (e) { }
+      delete layers[id];
+    }
+    layers[id] = createLayer(canvas[id], code);
+  } catch (e) {
+    console.error('Error in code object ' + id + '. Code not rendered. ' + e);
```
Comment (jonathanperret) [inline public/paysagerenderer.js]: I merged it as is but I think it’d look better with `, e` instead of `+ e` – it should make the stack trace clickable.
